apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: employapp-rs
  namespace: employapp
  labels:
    app: employees
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: employees
        image: 549079173707.dkr.ecr.us-east-1.amazonaws.com/employment-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: DBHOST
          value: "mysql-service.mysqlapp.svc.cluster.local"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "pw"
        - name: DATABASE
          value: "employees"
      imagePullSecrets:
        - name: ecr-secret
