apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: employment-app-rs
  namespace: employee-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: employment-app
        image: 549079173707.dkr.ecr.us-east-1.amazonaws.com/employment-app:latest
        resources:
          requests:
            cpu: 250m
            memory: 250Mi
          limits:
            cpu: 500m
            memory: 500Mi
        ports:
        - containerPort: 8080
        env:
        - name: DBHOST
          value: "mysql.mysql-db.svc.cluster.local"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "pw"
        - name: DATABASE
          value: "employees"
        - name: APP_COLOR
          value: "blue"
        readinessProbe:
          httpGet:
            path: "/health"
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
      imagePullSecrets:
      - name: ecr-secret
