apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: mysql-db
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: 549079173707.dkr.ecr.us-east-1.amazonaws.com/mysql:latest
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 200m
        memory: 200Mi
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "pw"
    - name: MYSQL_DATABASE
      value: "employees"
  imagePullSecrets:
  - name: ecr-secret
