apiVersion: v1
kind: Pod
metadata:
  name: mysqlapp-pod
  namespace: mysqlapp
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: 549079173707.dkr.ecr.us-east-1.amazonaws.com/mysql:latest
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "pw"
  imagePullSecrets:
  - name: ecr-secret
