apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: mysql-db
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: 549079173707.dkr.ecr.us-east-1.amazonaws.com/mysql:latest
    resources:
      requests:
        cpu: 500m
        memory: 500Mi
      limits:
        cpu: 1
        memory: 1Gi
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "pw"
    - name: MYSQL_DATABASE
      value: "employees"
    readinessProbe:
      exec:
        command: ["mysqladmin", "ping", "-h", "localhost"]
      initialDelaySeconds: 10
      periodSeconds: 5
  imagePullSecrets:
  - name: ecr-secret
