apiVersion: v1
kind: Pod
metadata:
  name: webapp
  namespace: employee-app
  labels:
    app: employees
spec:
  containers:
  - name: webapp
    image: nginx:latest
    ports:
    - containerPort: 80
