apiVersion: v1
kind: Pod
metadata:
  name: employment-app
  namespace: employee-app
  labels:
    app: employees
spec:
  containers:
  - name: employment-app
    image: 549079173707.dkr.ecr.us-east-1.amazonaws.com/employment-app:latest
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 200m
        memory: 200Mi
    ports:
    - containerPort: 8080
    env:
    - name: DBHOST
      value: "mysql.mysql-db.svc.cluster.local"
    - name: DBPORT
      value: "3306"
    - name: DBUSER
      value: "root"
    - name: DBPWD
      value: "pw"
    - name: DATABASE
      value: "employees"
    - name: APP_COLOR
      value: "blue"
