apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqlapp-deployment
  namespace: mysqlapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: 549079173707.dkr.ecr.us-east-1.amazonaws.com/mysql:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "pw"
      imagePullSecrets:
      - name: ecr-secret
