apiVersion: apps/v1
kind: Deployment
metadata:
  name: employment-app-deployment
  namespace: employee-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: employment-app
        image: 549079173707.dkr.ecr.us-east-1.amazonaws.com/employment-app:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
        ports:
        - containerPort: 8080
        env:
        - name: DBHOST
          value: "mysql.mysql-db.svc.cluster.local"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "pw"
        - name: DATABASE
          value: "employees"
        - name: APP_COLOR
          value: "pink"
