apiVersion: v1
kind: Service
metadata:
  name: employment-app-service
  namespace: employee-app
spec:
  type: NodePort
  selector:
    app: employees
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
