apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: employee-app
spec:
  type: NodePort
  selector:
    app: employees
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
